# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vert.x Hacks
email: paulo@mlopes.net
description: >
  an appropriate application of ingenuity
logo: "assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mlopes.net" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Paulo Lopes'
bio: >
  I'm Paulo and I've used my 10+ years of software development experience
  writing, rewriting, banging my head against the wall, editing and
  re-editing high-performance web application to make Vert.x an even more
  awesome framework.

author_image: "assets/images/author.jpg"
twitter_username: jetdrone
github_username:  pmlopes

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
